[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'rhysd/vim-textobj-word-column'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
hook_add = '''
    map <silent><Leader>ra <Plug>(operator-surround-append)
    map <silent><Leader>rd <Plug>(operator-surround-delete)
    map <silent><Leader>rr <Plug>(operator-surround-replace)

    if dein#is_sourced('vim-textobj-anyblock')
        nmap <silent><Leader>rdd <Plug>(operator-surround-delete)<Plug>(textobj-anyblock-a)
        nmap <silent><Leader>rrr <Plug>(operator-surround-replace)<Plug>(textobj-anyblock-a)
    endif
'''

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'osyo-manga/vim-textobj-blockwise'

[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
hook_add = '''
    map y <Plug>(operator-flashy)
    nmap Y <Plug>(operator-flashy)$
'''
