[[plugins]]
repo = "sheerun/vim-polyglot"
hook_add = """
let g:jsx_ext_required = 1
let g:polyglot_disabled = ['latex']
"""

[[plugins]]
repo = "JesseKPhillips/d.vim"

[[plugins]]
repo = "digitaltoad/vim-jade"

[[plugins]]
repo = "gf3/peg.vim"
