[[plugins]]
repo = "kana/vim-textobj-user"

[[plugins]]
repo = "kana/vim-operator-user"

[[plugins]]
repo = "kana/vim-textobj-indent"
depends = "vim-textobj-user"

[[plugins]]
repo = "rhysd/vim-textobj-word-column"

[[plugins]]
repo = "sgur/vim-textobj-parameter"

[[plugins]]
repo = "kana/vim-operator-replace"
hook_add = """
map _  <Plug>(operator-replace)
"""

[[plugins]]
repo = "kana/vim-textobj-entire"

[[plugins]]
repo = "haya14busa/vim-operator-flashy"
hook_add = """
map y <Plug>(operator-flashy)
nmap Y <Plug>(operator-flashy)$
"""

[[plugins]]
repo = "mopp/vim-operator-convert-case"
hook_add = """
nmap <Leader>cl <Plug>(operator-convert-case-lower-camel)
nmap <Leader>cu <Plug>(operator-convert-case-upper-camel)
nmap <Leader>sl <Plug>(operator-convert-case-lower-snake)
nmap <Leader>su <Plug>(operator-convert-case-upper-snake)
"""

[[plugins]]
repo = "machakann/vim-sandwich"
hook_post_source = """
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
"""
