[[plugins]]
repo = 'mopp/mopkai.vim'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'cocopon/iceberg.vim'
