[[plugins]]
repo = "JesseKPhillips/d.vim"

[[plugins]]
repo = "digitaltoad/vim-jade"

[[plugins]]
repo = "gf3/peg.vim"

[[plugins]]
repo = "vim-scripts/lojban"

[[plugins]]
repo = "qnighy/satysfi.vim"
