[[plugins]]
repo = "JesseKPhillips/d.vim"

[[plugin]]
repo = "elzr/vim-json"
hook_add = """
let g:vim_json_syntax_conceal = 0
"""

[[plugins]]
repo = "digitaltoad/vim-jade"

[[plugins]]
repo = "gf3/peg.vim"

[[plugins]]
repo = "vim-scripts/lojban"

[[plugins]]
repo = "qnighy/satysfi.vim"
