theme = "nord-dark"

[icons]
name = "awesome5"
[icons.overrides]
cpu = "\uf0e4"
microphone_empty = "\uf130"
microphone_full = "\uf130"
microphone_half = "\uf130"
microphone_muted = "\uf131"

[[block]]
block = "custom"
interval = 1
command = 'echo  $(xclip -o -sel clip | xargs | rg -o "^.{0,32}")'

[[block]]
block = "net"
format = "{speed_down;K*b}ps{speed_up;K*b}ps"
interval = 1

[[block]]
block = "speedtest"
interval = 600
format = "\uf0ac{speed_down;K*b}ps{speed_up;K*b}ps"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "{path}{available}"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "{path} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "CPU:{max}C"
idle = 80
info = 90
chip = "k10temp-*"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "GPU:{max}C"
idle = 80
info = 90
chip = "amdgpu-pci-0b00"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "weather"
format = "{temp}C {humidity}%"
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "custom"
interval = 60
command = 'curl -sS "https://map.yahooapis.jp/weather/V1/place?coordinates=139.7699064,35.6714754&output=json&appid=$YAHOO_APPID" | jq ".Feature[0].Property.WeatherList.Weather[1:6][].Rainfall" | xargs echo '

[[block]]
block = "sound"
format = ""
device_kind = "source"

[[block]]
block = "custom"
interval = 1
command = 'echo  $(date "+%Y(%EC%Ey)年%m月%d日%A %H時%M分%S秒")'
